// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkdvmbkkkjzvkkvvhlqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZHZtYmtra2p6dmtrdnZobHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTE3NTcsImV4cCI6MjA2NzYyNzc1N30.uOPnMH3WEibc04xy-LgTfMLYNJ5ZC3h1Bmx6i4u00Zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});